#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

_i = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAZlJ"
    "REFUWIXtlb9KA0EQxr9JFS3ESlKJpLIQkRRiYW1pGfIMvo3kAVJZW6ZRfAJLCxG0SiGKZyMI"
    "4VibPRkuM7Oze9rlgyNhd+ab3/4H1srTiIiC8dX/UpWIHhKFVz4A47+ovSkY9xkYbweAEyG+"
    "TEQ0NUY35xAAZkJ+OUSi+LnDYjf+PpVArEx7C6CKkKYp659lQbDgAwWick7vcezfAvDlguC7"
    "ncMkZsQzGP6/50rwAJijWfUcSHmcZuQxbBRCIGfoR/x9N6OkKeoycqajmPdIRG8xf2IBcN1K"
    "y5IJ0HgvjDp6h9K+XQBwJ/npO9LWZ25CCEGETgI0m63TvW7INQMR4jlC7BXWujF7nTv8kJ2G"
    "64JTsR9zlhbAacpFOZoX3jwAg1RAyqg27ogdB8CvSk+BmkdErwDuhfapx3ic88jkvBPu/cJM"
    "XkoBjPhFEqBFe1UAUWtxoo9VAABCCN8ANqwYLv5K8n7t9VQ3E7sB+9FoqMUKRS49xV0S1reK"
    "4Get9qGwHMk195L12mubUqdRJzRRNt8S2g23lqEfQ2Ya8R2KMBsAAAAASUVORK5CYII=")

get_Icon = _i.getIcon